<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TrainModel\TrainModel.Core\TrainModel.Core.csproj" />
    <ProjectReference Include="..\..\src\TrackModel\TrackModel.Core\TrackModel.Core.csproj" />
    <ProjectReference Include="..\..\src\TrainController\TrainController.Core\TrainController.Core.csproj" />
    <ProjectReference Include="..\..\src\TrackController\TrackController.Core\TrackController.Core.csproj" />
    <ProjectReference Include="..\..\src\CTC\CTC.Core\CTC.Core.csproj" />
    <ProjectReference Include="..\..\src\Shared\TrainControl.Contracts\TrainControl.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Shared\TrainControl.Common\TrainControl.Common.csproj" />
  </ItemGroup>

</Project>
